name = "kgikbot"
main = "src/index.js"
compatibility_date = "2024-12-01"

[durable_objects]
bindings = [
  { name = "TradeLogDO", class_name = "TradeLogDO" }
]

[migrations]
[[migrations]]
tag = "v1"
new_classes = ["TradeLogDO"]